### ISSUE TITLE
Address Header Critical Accessibility issues

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#856]
This ticket covers accessibility issues that need to be addressed in order to remain compliant with WCAG. 

- [x] Menu items not available when resized or zoomed (WCAG 1.4.4).
- [x] Ensure the USTP logo is labeled as decorative. (WCAG 1.1.1)
- [x] Ensure that the currently selected navigation tab can be programmatically determined. (WCAG 1.3.2).

**Comment by fmaddenflx** [comment]
I’ve been working with ChatGPT all morning to get the voiceover to read the page properly and also update the user after selecting one of the items in the header primary navigation.
This has become quite involved, but I also feel this is critical for accessibility.  This Affects the loading behavior of ever screen in our app.

Part of this process was installing the eslint plugin for jsx-a11y.  This has now brought numerous issues to my attention and the app doesn’t load due to pa11y related errors, such as the use of tabIndex on elements that are non-interactive.
